# Generated by Django 5.2.12 on 2026-03-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="UPA-YOLOv7-Tiny", max_length=100),
                ),
                ("model_version", models.CharField(default="1.0", max_length=50)),
                (
                    "map50",
                    models.FloatField(blank=True, null=True, verbose_name="mAP@0.5"),
                ),
                (
                    "map50_95",
                    models.FloatField(
                        blank=True, null=True, verbose_name="mAP@0.5:0.95"
                    ),
                ),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                (
                    "gflops",
                    models.FloatField(blank=True, null=True, verbose_name="GFLOPs"),
                ),
                (
                    "parameters_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Parameters (M)"
                    ),
                ),
                ("avg_inference_time_ms", models.FloatField(blank=True, null=True)),
                ("dataset_name", models.CharField(blank=True, max_length=200)),
                ("training_epochs", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Model Metrics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("input_file", models.FileField(upload_to="detection/inputs/")),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="detection/outputs/"
                    ),
                ),
                (
                    "annotated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="detection/annotated/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("inference_time_ms", models.FloatField(blank=True, null=True)),
                ("total_detections", models.IntegerField(default=0)),
                ("confidence_threshold", models.FloatField(default=0.25)),
                ("iou_threshold", models.FloatField(default=0.45)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("sea_cucumber", "Sea Cucumber"),
                            ("sea_urchin", "Sea Urchin"),
                            ("shell", "Shell"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("bbox_x", models.FloatField()),
                ("bbox_y", models.FloatField()),
                ("bbox_w", models.FloatField()),
                ("bbox_h", models.FloatField()),
                ("pixel_x1", models.IntegerField(default=0)),
                ("pixel_y1", models.IntegerField(default=0)),
                ("pixel_x2", models.IntegerField(default=0)),
                ("pixel_y2", models.IntegerField(default=0)),
                ("frame_number", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="detection.detectionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence"],
            },
        ),
    ]
