# Generated by Django 5.2.12 on 2026-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionresult",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
